[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "zbar"]

[phases.install]
cmds = [
  "python3.12 -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip",
  "/opt/venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/python bot.py"
